### ISSUE TITLE
Add an 'ignore' argument to find()

### ISSUE THREAD

**Issue by stephanepechard** [datafolklabs/backpedal#2]
The `find` method is interesting and goes beyond the known `os.walk` but adding a way to ignore some files or directories names would make it even more useful. Value could be a tuple of strings or a file like `.gitignore`.
What do you think of it?

**Comment by derks** [comment]
@stephanepechard absolutely! This would make for an obvious improvement.  Will add it!

**Comment by derks** [comment]
Pushed out `0.9.10` .. you can now pass an `ignore` list:

```python
import backpedal

backpedal.find('README.md', ignore=['(.*)\.git(.*)'])
```
